packages:
  - apps/*
allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  '@swc/core': true
  '@tarojs/binding': true
  '@tarojs/cli': true
  core-js: true
  core-js-pure: true
  esbuild: true
  prisma: true
  sharp: true
minimumReleaseAgeExclude:
  - prettier@3.9.0
